### PR TITLE
feat: export typings

### PR DESCRIPTION
**Pull request by WeebHiroyuki**
This pull request addresses an enhancement requested in #53. It exports the interfaces in the index.d.ts (index typings declaration) file.

### CODE REVIEW

**Comment by reboxer** [comment]
Sorry for taking so long, thanks 👍

**Comment by reboxer** [comment]
@WeebHiroyuki It looks like a missed something with this PR. Exporting all interfaces this way, all typings will be missing when using VSC's intellisense unless you require `default`, but this requires the typings and not the library.
So unless there is a way to fix it from the typings file alone, i will have to revert this PR.

**Comment by WeebHiroyuki** [comment]
Ah I understand. I'll work on a fix. Sorry about that.

**Comment by WeebHiroyuki** [comment]
I don't think it's possible to export the interfaces and `export = OAuth`. The `export = OAuth;` would override the exported interfaces, exporting `OAuth` alone.
Another possible solution would be to have no default export, and instead export `OAuth`. Instead of importing `OAuth` like `const OAuth = require('discord-oauth2');`, you'd import it _from_ the library (i.e., `const { OAuth } = require('discord-oauth2');`).

**Comment by reboxer** [comment]
Sorry but since there is no solution from the typings file alone, i'll have to revert these changes.
You can grab the typings and use them in your project if you want.

**Pull request merged**
